version: "3"

services:
  postgres:
    image: postgres:11.5
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_USER: hr-services
      POSTGRES_PASSWORD: development_hr_services_2019
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres: ~
